In [1]:
import torch
import numpy as np
np.set_printoptions(precision=3)

In [5]:
a_list = [1, 2, 3]
a_numpy = np.array(a_list, dtype=np.int32)
a_tensor = torch.tensor(a_list, dtype=torch.int32)
a_tensor_from_numpy = torch.from_numpy(a_numpy)
print('list: ', a_list)
print('numpy: ', a_numpy)
print('torch tensor: ', a_tensor)
print('tensor from numpy: ', a_tensor_from_numpy)

list:  [1, 2, 3]
numpy:  [1 2 3]
torch tensor:  tensor([1, 2, 3], dtype=torch.int32)
tensor from numpy:  tensor([1, 2, 3], dtype=torch.int32)


In [8]:
t_ones = torch.ones(2, 3)
print('tensor 2x3: ', t_ones)
print('shape: ', t_ones.shape)

tensor 2x3:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
shape:  torch.Size([2, 3])


In [9]:
# tensor of random values
t_rand = torch.rand(2, 3)
print(t_rand)

tensor([[0.6765, 0.0925, 0.7344],
        [0.5332, 0.3600, 0.8599]])


In [11]:
# changing data type
a_tensor_new = a_tensor.to(torch.int64)
print(a_tensor_new, a_tensor_new.dtype)

tensor([1, 2, 3]) torch.int64


In [14]:
# transposing tensor
t = torch.rand(3, 5)
t_tr = torch.transpose(t, 0, 1)
print(t.shape, ' --> ', t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])


In [15]:
# reshaping a tensor
t = torch.zeros(30)
t_reshape = t.reshape(5, 6)
print(t_reshape.shape)

torch.Size([5, 6])


In [17]:
# removing unnecessary dimensions
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


In [18]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

In [20]:
# element-wise product
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [21]:
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])


In [23]:
# matrix product t1 * t2^T
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [28]:
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(t1)
print(norm_t1)

tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])
tensor(0.0739)
